name: 'Terraform-aws'

on:
  push:
    branches:
      - main
    paths:
      - 'aws/*.tf'
      - '.github/workflows/terraform-aws.yml'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: aws
      run: |
          terraform init \
          -backend-config=access_key=${{ secrets.BACKEND_STORAGE_ACCOUNT_ACCESS_KEY }} \
          -backend-config=key="aws-poc.terraform.tfstate"
          
    - name: Setup Terraform variables
      working-directory: aws
      id: vars
      run: |-
          cat > terraform.tfvars <<EOF
          aws_access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws_secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws_account_id = "492737776546"
          vpc_id = "vpc-0246d74eae7c1aa94"
          region = "us-east-1"
          plendpointservice = "com.amazonaws.vpce.us-east-1.vpce-svc-0860154777d8dec0b"
          subnets_to_privatelink = {
            "use1-az1" = "subnet-0620ef8e739b28eaa",
            "use1-az2" = "subnet-013cb394df5b1c447",
            "use1-az3" = "subnet-013cb394df5b1c447",
            "use1-az4" = "subnet-0de2aacb446c91fc0",
            "use1-az5" = "subnet-013cb394df5b1c447",
          }
          EOF
          cat terraform.tfvars
          
    # Checks that all Terraform configuration files adhere to a canonical format

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      working-directory: aws
      run: terraform plan -var-file=terraform.tfvars

      # On push to "main", build or change infrastructure according to Terraform configuration file
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      working-directory: aws
      run: terraform apply -auto-approve -var-file=terraform.tfvars
